name: Create Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Release Type"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version from package.json
        id: package_version
        run: |
          version=$(node -p "require('./package.json').version")
          echo "current_version=v${version}" >> $GITHUB_OUTPUT

      - name: Calculate next version
        id: next_version
        run: |
          current_version=${{ steps.package_version.outputs.current_version }}
          IFS='.' read -r major minor patch <<< "${current_version#v}"

          case "${{ github.event.inputs.release_type }}" in
            "major")
              new_version="$((major + 1)).0.0"
              ;;
            "minor")
              new_version="${major}.$((minor + 1)).0"
              ;;
            "patch")
              new_version="${major}.${minor}.$((patch + 1))"
              ;;
          esac

          echo "version=${new_version}" >> $GITHUB_OUTPUT

      - name: Manual Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          VERSION: ${{ steps.next_version.outputs.version }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          # Update version in package.json
          npm version $VERSION --no-git-tag-version

          # Commit the version change
          git add .
          git commit -m "chore(release): v${VERSION}"

          # Push the version change commit
          git push

      - name: Generate Changelog
        id: changelog
        run: |
          PREVIOUS_TAG=$(git describe --tags --abbrev=0)
          REPO="${GITHUB_REPOSITORY}"
          NEW_TAG="v${{ steps.next_version.outputs.version }}"
          {
            echo "CHANGELOG<<EOF"
            echo "## What's Changed"
            echo ""
            git log --pretty=format:"- %s in ${REPO}#%h" ${PREVIOUS_TAG}..HEAD
            echo ""
            echo ""
            echo "**Full Changelog**: https://github.com/${REPO}/compare/${PREVIOUS_TAG}...${NEW_TAG}"
            echo "EOF"
          } >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.next_version.outputs.version }}
          release_name: v${{ steps.next_version.outputs.version }}
          body: ${{ env.CHANGELOG }}
          draft: false
          prerelease: false
